package com.coveragetool.report;

import com.coveragetool.model.*;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.util.Map;
import java.util.Map;
import java.util.Map;

/**
 * 报告生成器 - 生成HTML格式的测试覆盖分析报告
 * 
 * 这个类负责将分析结果转换为可读的HTML报告。
 */
public class ReportGenerator {
    
    /**
     * JSON序列化器
     */
    private Gson gson;
    
    /**
     * 构造函数
     */
    public ReportGenerator() {
        this.gson = new GsonBuilder()
            .setPrettyPrinting()
            .setDateFormat("yyyy-MM-dd HH:mm:ss")
            .create();
    }
    
    /**
     * 生成HTML报告
     * 
     * @param result 分析结果
     * @return HTML报告字符串
     */
    public String generateHTMLReport(AnalysisResult result) {
        StringBuilder html = new StringBuilder();
        
        // HTML头部
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"zh-CN\">\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("    <title>Java单元测试覆盖分析报告</title>\n");
        html.append("    <style>\n");
        html.append(getReportStyles());
        html.append("    </style>\n");
        html.append("</head>\n");
        html.append("<body>\n");
        
        // 报告标题
        html.append("    <div class=\"container\">\n");
        html.append("        <header>\n");
        html.append("            <h1>Java单元测试覆盖分析报告</h1>\n");
        html.append("            <div class=\"info\">\n");
        html.append("                <p><strong>项目：</strong>")
            .append(result.getProjectInfo().getProjectName()).append("</p>\n");
        html.append("                <p><strong>分析时间：</strong>")
            .append(result.getAnalysisTime()).append("</p>\n");
        html.append("                <p><strong>总体覆盖率：</strong><span class=\"coverage\">")
            .append(String.format("%.2f", result.getCoverageReport().getOverallCoverage()))
            .append("%</span></p>\n");
        html.append("            </div>\n");
        html.append("        </header>\n");
        
        // 覆盖率统计
        html.append("        <section class=\"statistics\">\n");
        html.append("            <h2>覆盖率统计</h2>\n");
        html.append(generateStatisticsSection(result.getCoverageReport()));
        html.append("        </section>\n");
        
        // 未覆盖方法列表
        html.append("        <section class=\"uncovered\">\n");
        html.append("            <h2>未覆盖的方法</h2>\n");
        html.append(generateUncoveredMethodsSection(result.getCoverageReport()));
        html.append("        </section>\n");
        
        // 测试粒度分布
        html.append("        <section class=\"granularity\">\n");
        html.append("            <h2>测试粒度分布</h2>\n");
        html.append(generateGranularitySection(result.getCoverageReport()));
        html.append("        </section>\n");
        
        // 开发者统计
        if (result.getGitStatistics() != null) {
            html.append("        <section class=\"developers\">\n");
            html.append("            <h2>开发者统计</h2>\n");
            html.append(generateDeveloperSection(result.getGitStatistics()));
            html.append("        </section>\n");
        }
        
        // 页脚
        html.append("        <footer>\n");
        html.append("            <p>Generated by Java Coverage Tool</p>\n");
        html.append("        </footer>\n");
        html.append("    </div>\n");
        html.append("</body>\n");
        html.append("</html>");
        
        return html.toString();
    }
    
    /**
     * 生成统计部分
     */
    private String generateStatisticsSection(CoverageReport report) {
        StringBuilder sb = new StringBuilder();
        sb.append("            <div class=\"stats-grid\">\n");
        sb.append("                <div class=\"stat-card\">\n");
        sb.append("                    <h3>业务类</h3>\n");
        sb.append("                    <p class=\"stat-number\">").append(report.getTotalBusinessClasses()).append("</p>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"stat-card\">\n");
        sb.append("                    <h3>测试类</h3>\n");
        sb.append("                    <p class=\"stat-number\">").append(report.getTotalTestClasses()).append("</p>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"stat-card\">\n");
        sb.append("                    <h3>总方法数</h3>\n");
        sb.append("                    <p class=\"stat-number\">").append(report.getTotalMethods()).append("</p>\n");
        sb.append("                </div>\n");
        sb.append("                <div class=\"stat-card\">\n");
        sb.append("                    <h3>已覆盖方法</h3>\n");
        sb.append("                    <p class=\"stat-number\">").append(report.getCoveredMethods()).append("</p>\n");
        sb.append("                </div>\n");
        sb.append("            </div>\n");
        return sb.toString();
    }
    
    /**
     * 生成未覆盖方法列表
     */
    private String generateUncoveredMethodsSection(CoverageReport report) {
        StringBuilder sb = new StringBuilder();
        sb.append("            <table>\n");
        sb.append("                <thead>\n");
        sb.append("                    <tr>\n");
        sb.append("                        <th>类名</th>\n");
        sb.append("                        <th>方法名</th>\n");
        sb.append("                        <th>复杂度</th>\n");
        sb.append("                    </tr>\n");
        sb.append("                </thead>\n");
        sb.append("                <tbody>\n");
        
        for (MethodCoverage method : report.getUncoveredMethodList()) {
            sb.append("                    <tr>\n");
            sb.append("                        <td>").append(method.getClassName()).append("</td>\n");
            sb.append("                        <td>").append(method.getMethodName()).append("</td>\n");
            sb.append("                        <td>").append(method.getComplexity()).append("</td>\n");
            sb.append("                    </tr>\n");
        }
        
        sb.append("                </tbody>\n");
        sb.append("            </table>\n");
        return sb.toString();
    }
    
    /**
     * 生成测试粒度分布
     */
    private String generateGranularitySection(CoverageReport report) {
        StringBuilder sb = new StringBuilder();
        sb.append("            <div class=\"granularity-grid\">\n");
        
        for (Map.Entry<GranularityLevel, Integer> entry : 
             report.getGranularityDistribution().entrySet()) {
            sb.append("                <div class=\"granularity-card level-")
              .append(entry.getKey().name().toLowerCase()).append("\">\n");
            sb.append("                    <h3>").append(entry.getKey().getDisplayName()).append("</h3>\n");
            sb.append("                    <p class=\"stat-number\">").append(entry.getValue()).append("</p>\n");
            sb.append("                </div>\n");
        }
        
        sb.append("            </div>\n");
        return sb.toString();
    }
    
    /**
     * 生成开发者统计
     */
    private String generateDeveloperSection(GitStatistics gitStats) {
        StringBuilder sb = new StringBuilder();
        sb.append("            <table>\n");
        sb.append("                <thead>\n");
        sb.append("                    <tr>\n");
        sb.append("                        <th>开发者</th>\n");
        sb.append("                        <th>提交次数</th>\n");
        sb.append("                        <th>新增行数</th>\n");
        sb.append("                        <th>删除行数</th>\n");
        sb.append("                    </tr>\n");
        sb.append("                </thead>\n");
        sb.append("                <tbody>\n");
        
        for (DeveloperStats stats : gitStats.getDeveloperStats().values()) {
            sb.append("                    <tr>\n");
            sb.append("                        <td>").append(stats.getDeveloperName()).append("</td>\n");
            sb.append("                        <td>").append(stats.getTotalCommits()).append("</td>\n");
            sb.append("                        <td>").append(stats.getTotalLinesAdded()).append("</td>\n");
            sb.append("                        <td>").append(stats.getTotalLinesDeleted()).append("</td>\n");
            sb.append("                    </tr>\n");
        }
        
        sb.append("                </tbody>\n");
        sb.append("            </table>\n");
        return sb.toString();
    }
    
    /**
     * 获取报告样式
     */
    private String getReportStyles() {
        return "        body {\n" +
               "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n" +
               "            background: #f5f5f5;\n" +
               "            margin: 0;\n" +
               "            padding: 20px;\n" +
               "        }\n" +
               "        .container {\n" +
               "            max-width: 1200px;\n" +
               "            margin: 0 auto;\n" +
               "            background: white;\n" +
               "            padding: 30px;\n" +
               "            border-radius: 8px;\n" +
               "            box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n" +
               "        }\n" +
               "        header {\n" +
               "            border-bottom: 2px solid #4CAF50;\n" +
               "            padding-bottom: 20px;\n" +
               "            margin-bottom: 30px;\n" +
               "        }\n" +
               "        h1 {\n" +
               "            color: #333;\n" +
               "            margin-bottom: 10px;\n" +
               "        }\n" +
               "        .coverage {\n" +
               "            color: #4CAF50;\n" +
               "            font-size: 24px;\n" +
               "            font-weight: bold;\n" +
               "        }\n" +
               "        .stats-grid, .granularity-grid {\n" +
               "            display: grid;\n" +
               "            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n" +
               "            gap: 20px;\n" +
               "            margin: 20px 0;\n" +
               "        }\n" +
               "        .stat-card, .granularity-card {\n" +
               "            background: #f9f9f9;\n" +
               "            padding: 20px;\n" +
               "            border-radius: 8px;\n" +
               "            text-align: center;\n" +
               "        }\n" +
               "        .stat-number {\n" +
               "            font-size: 32px;\n" +
               "            font-weight: bold;\n" +
               "            color: #333;\n" +
               "        }\n" +
               "        table {\n" +
               "            width: 100%;\n" +
               "            border-collapse: collapse;\n" +
               "            margin: 20px 0;\n" +
               "        }\n" +
               "        th, td {\n" +
               "            padding: 12px;\n" +
               "            text-align: left;\n" +
               "            border-bottom: 1px solid #ddd;\n" +
               "        }\n" +
               "        th {\n" +
               "            background-color: #4CAF50;\n" +
               "            color: white;\n" +
               "        }\n" +
               "        tr:hover {\n" +
               "            background-color: #f5f5f5;\n" +
               "        }\n" +
               "        footer {\n" +
               "            margin-top: 40px;\n" +
               "            padding-top: 20px;\n" +
               "            border-top: 1px solid #ddd;\n" +
               "            text-align: center;\n" +
               "            color: #666;\n" +
               "        }\n";
    }
}
